#!/usr/bin/env python3
import os

def get_refine_paths(direpa_src, direpa_dst, index=None) -> tuple[list, int]:
   _refines= [
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**/logs",
         ],
         discarded=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         not_discarded=[
            "build",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/build/debug.log",
            "logs/debug.log",
         ],
         patterns=[
            "**/logs/debug.log",
         ],
         discarded=[
            "build/logs/debug.log",
            "logs/debug.log",
         ],
         not_discarded=[
            "logs/build/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            ".log",
            "debug.log",
            "foo.log",
            "logs/debug.log",
         ],
         patterns=[
            "*.log",
         ],
         discarded=[
            ".log",
            "debug.log",
            "foo.log",
            "logs/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug.log",
            "important.log",
            "logs/important.log",
            "trace.log",
         ],
         patterns=[
            "*.log",
            "!important.log",
         ],
         discarded=[
            "debug.log",
            "trace.log",
         ],
         not_discarded=[
            "important.log",
            "logs/important.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug.log",
            "important/debug.log",
            "important/trace.log",
         ],
         patterns=[
            "*.log",
            "!important/*.log",
            "trace.*",
         ],
         discarded=[
            "debug.log",
            "important/trace.log",
         ],
         not_discarded=[
            "important/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug.log",
            "logs/debug.log",
         ],
         patterns=[
            "/debug.log",
         ],
         discarded=[
            "debug.log",
         ],
         not_discarded=[
            "logs/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug.log",
            "logs/debug.log",
         ],
         patterns=[
            "debug.log",
         ],
         discarded=[
            "debug.log",
            "logs/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug0.log",
            "debug10.log",
            "debugg.log",
         ],
         patterns=[
            "debug?.log",
         ],
         discarded=[
            "debug0.log",
            "debugg.log",
         ],
         not_discarded=[
            "debug10.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug0.log",
            "debug1.log",
            "debug10.log",
         ],
         patterns=[
            "debug[0-9].log",
         ],
         discarded=[
            "debug0.log",
            "debug1.log",
         ],
         not_discarded=[
            "debug10.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug0.log",
            "debug01.log",
            "debug1.log",
            "debug2.log",
         ],
         patterns=[
            "debug[01].log",
         ],
         discarded=[
            "debug0.log",
            "debug1.log",
         ],
         not_discarded=[
            "debug01.log",
            "debug2.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug0.log",
            "debug01.log",
            "debug1.log",
            "debug2.log",
         ],
         patterns=[
            "debug[!01].log",
         ],
         discarded=[
            "debug2.log",
         ],
         not_discarded=[
            "debug0.log",
            "debug01.log",
            "debug1.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "debug1.log",
            "debuga.log",
            "debugb.log",
         ],
         patterns=[
            "debug[a-z].log",
         ],
         discarded=[
            "debuga.log",
            "debugb.log",
         ],
         not_discarded=[
            "debug1.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/",
            "build/logs/debug.log",
            "logs/",
            "logs/debug.log",
            "logs/latest/foo.bar",
         ],
         patterns=[
            "logs",
         ],
         discarded=[
            "build/logs",
            "build/logs/debug.log",
            "logs",
            "logs/debug.log",
            "logs/latest/foo.bar",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/foo.bar",
            "build/logs/latest/debug.log",
            "logs/debug.log",
            "logs/latest/foo.bar",
         ],
         patterns=[
            "logs/",
         ],
         discarded=[
            "build/logs/foo.bar",
            "build/logs/latest/debug.log",
            "logs/debug.log",
            "logs/latest/foo.bar",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "logs/debug.log",
            "logs/important.log",
         ],
         patterns=[
            "logs/",
            "!logs/important.log",
         ],
         discarded=[
            "logs/debug.log",
            "logs/important.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "logs/debug.log",
            "logs/monday/debug.log",
            "logs/monday/pm/debug.log",
         ],
         patterns=[
            "logs/**/debug.log",
         ],
         discarded=[
            "logs/debug.log",
            "logs/monday/debug.log",
            "logs/monday/pm/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "logs/latest/debug.log",
            "logs/monday/debug.log",
            "logs/tuesday/debug.log",
         ],
         patterns=[
            "logs/*day/debug.log",
         ],
         discarded=[
            "logs/monday/debug.log",
            "logs/tuesday/debug.log",
         ],
         not_discarded=[
            "logs/latest/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "debug.log",
            "logs/debug.log",
         ],
         patterns=[
            "logs/debug.log",
         ],
         discarded=[
            "logs/debug.log",
         ],
         not_discarded=[
            "build/logs/debug.log",
            "debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**/logs",
         ],
         discarded=[
            os.path.join(direpa_src, "build/logs/debug.log"),
            os.path.join(direpa_src, "logs/debug.log"),
            os.path.join(direpa_src, "logs/monday/foo.bar"),
         ],
         not_discarded=[
            os.path.join(direpa_src, "build"),
         ],
         get_abs_paths=True,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**/logs",
         ],
         discarded=[
            os.path.join(direpa_src, "build/logs/debug.log"),
            os.path.join(direpa_src, "logs/debug.log"),
            os.path.join(direpa_src, "logs/monday/foo.bar"),
         ],
         not_discarded=[
            os.path.join(direpa_src, "build"),
         ],
         get_abs_paths=True,
         keep_empty_dir=True,
         test_filenpa_patterns=True,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**/logs",
         ],
         discarded=[
            os.path.join(direpa_dst, "build/logs/debug.log"),
            os.path.join(direpa_dst, "logs/debug.log"),
            os.path.join(direpa_dst, "logs/monday/foo.bar"),
         ],
         not_discarded=[
            os.path.join(direpa_dst, "build"),
         ],
         get_abs_paths=True,
         keep_empty_dir=True,
         test_filenpa_patterns=True,
         test_direpa_dst=True,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**/logs",
         ],
         discarded=[
            os.path.join(direpa_dst, "build/logs/debug.log"),
            os.path.join(direpa_dst, "logs/debug.log"),
            os.path.join(direpa_dst, "logs/monday/foo.bar"),
         ],
         not_discarded=[
         ],
         get_abs_paths=True,
         keep_empty_dir=False,
         test_filenpa_patterns=True,
         test_direpa_dst=True,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "/",
         ],
         discarded=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         not_discarded=[],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "/*",
         ],
         discarded=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         not_discarded=[],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**/",
         ],
         discarded=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         not_discarded=[],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "*",
         ],
         discarded=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         not_discarded=[],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**",
         ],
         discarded=[
            "build/logs/debug.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         not_discarded=[],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "build/logs/debug.log",
            "build/logs/trace.log",
            "logs/debug.log",
            "logs/monday/foo.bar",
         ],
         patterns=[
            "**/build",
            "!build/logs/trace.log",
         ],
         discarded=[
            "build/logs/debug.log",
         ],
         not_discarded=[
            "logs/debug.log",
            "logs/monday/foo.bar",
            "build/logs/trace.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "aaa/bbb/",
            "aaa/ccc/",
            "aaa/ccc/debug.log",
         ],
         patterns=[
            "aaa/*",
            "!aaa/ccc",
         ],
         discarded=[
            "aaa/bbb",
         ],
         not_discarded=[
            "aaa/ccc/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "foo/",
            "foo/bar/",
            "foo/bar/debug.log",
            "foo/other/info.log",
         ],
         patterns=[
            "/*",
            "!/foo",
            "/foo/*",
            "!/foo/bar",
         ],
         discarded=[
            "foo/other",
         ],
         not_discarded=[
            "foo/bar/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "aaa/bbb/",
            "aaa/ccc/",
            "aaa/ccc/debug.log",
         ],
         patterns=[
            "aaa/*",
            "!aaa/ccc",
         ],
         discarded=[
            "aaa/bbb",
         ],
         not_discarded=[
            "aaa/ccc/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "log.png",
            "foo/log.png",
            "foo/bar/debug.log",
         ],
         patterns=[
            "/*",
            "!/foo/*",
         ],
         discarded=[
            "log.png",
            "foo/log.png",
            "foo/bar/debug.log",
         ],
         not_discarded=[],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "log.png",
            "foo/log.png",
            "foo/bar/debug.log",
         ],
         patterns=[
            "/*",
            "!/foo/**",
         ],
         discarded=[
            "log.png",
            "foo/log.png",
            "foo/bar/debug.log",
         ],
         not_discarded=[],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),
      dict(
         paths=[
            "log.png",
            "foo/log.png",
            "foo/bar/debug.log",
         ],
         patterns=[
            "/*",
            "!/foo",
         ],
         discarded=[
         ],
         not_discarded=[
            "foo/log.png",
            "foo/bar/debug.log",
         ],
         get_abs_paths=False,
         keep_empty_dir=True,
         test_filenpa_patterns=False,
         test_direpa_dst=False,
      ),


   ]

   if index is None:
      return _refines, len(_refines) - 1
   else:
      if index == "last":
         return [_refines[-1]], len(_refines) - 1
      else:
         return [_refines[index]], len(_refines) - 1

